- rosbridge_server/setup.py
Copy fail-over build_ext code from Tornado's setup.py.
Fixes #135
> Build Tornado speedups

- rosapi/CMakeLists.txt
- rosapi/scripts/rosapi
- rosapi/src/rosapi/proxy.py
- rosapi/srv/ServicesForType.srv
update for find a list of service as specific service type
> Add finding service function as specific service type

- rosapi/CMakeLists.txt
- rosapi/scripts/rosapi_node
- rosbridge_server/launch/rosbridge_tcp.launch
- rosbridge_server/launch/rosbridge_websocket.launch
> rename rosapi script to rosapi_node to address #170

- rosbridge_library/src/rosbridge_library/internal/services.py
Pull request suggestion for issue https://github.com/RobotWebTools/roslibjs/issues/173
> Fixed namespacing services

- rosbridge_library/src/rosbridge_library/capabilities/subscribe.py
- rosbridge_library/src/rosbridge_library/internal/publishers.py
Related issue:
https://github.com/RobotWebTools/rosbridge_suite/issues/188
> Not apply compression option when multi clients subscribe same topic.

- rosbridge_server/scripts/rosbridge_udp.py
- rosbridge_server/scripts/rosbridge_websocket.py
- rosbridge_server/src/rosbridge_server/tcp_handler.py
- rosbridge_server/src/rosbridge_server/udp_handler.py
- rosbridge_server/src/rosbridge_server/websocket_handler.py
now rosbridge_websocket and rosbridge_udp really use the parameters added in #205
> actually use those parameters

- rosbridge_library/src/rosbridge_library/capabilities/defragmentation.py
I am changing the `log_msg` type from list to string by assignment everytime, shouldn't be a problem beside creating a list and joining it in the end, it should be better this way.
> Replaced += with ''.join() for python code

- rosbridge_server/package.xml
> Track Twisted run_depend

- rosapi/CMakeLists.txt
- rosapi/scripts/rosapi_node
- rosapi/src/rosapi/objectutils.py
- rosapi/src/rosapi/proxy.py
- rosapi/srv/NodeDetails.srv
- rosapi/srv/Topics.srv
- rosapi/srv/TopicsTypes.srv
UPDATED
- Get node details: subscriptions, publishing topics and services
There's also a pull request RosLibJS side for those services
https://github.com/RobotWebTools/roslibjs/pull/234
> New service and types of topics

- rosapi/CMakeLists.txt
- rosapi/scripts/rosapi_node
- rosapi/src/rosapi/proxy.py
- rosapi/srv/GetActionServers.srv
New rosapi service: get actionlib servers.
For a new widget that I'm developing
> New rosapi service: get actionlib servers

- rosbridge_server/src/rosbridge_server/udp_handler.py
> don't try to set TCP nodelay option for UDP

- .travis.yml
- rosbridge_library/CMakeLists.txt
- rosbridge_library/package.xml
- rosbridge_library/test/capabilities/test_call_service.py
Now, it tests against xenial and kinetic.
Please Squash and merge.
closes #282
> Cleaning up travis configuration

- rosapi/scripts/rosapi_node
Also refactors the way the parameters are obtained. Fixes #291
> Removes array delimiters while parsing parameters

- rosapi/scripts/rosapi_node
- rosapi/src/rosapi/glob_helper.py
- rosapi/src/rosapi/proxy.py
The api is now able to handle empty globs. Meaning that the service calls are now functional even if all the topics/services/params are exposed. Fixes #296
> Handles empty globes properly

- rosbridge_library/src/rosbridge_library/protocol.py
Checks for lists that have binary content as well as dicts
> Fixes #313 by fixing has_binary in protocol.py

- rosbridge_library/src/rosbridge_library/internal/message_conversion.py
Add missing argument to InvalidMessageException constructor
> Add missing argument to InvalidMessageException

- rosapi/src/rosapi/objectutils.py
- rosapi/src/rosapi/params.py
- rosbridge_server/src/rosbridge_server/udp_handler.py
* `xrange` is not available in Python3, `range` works for both Python versions
* the variable `v` is undefined in `search_param`, comparing the implementation with the sibling functions I expect `name` to be the intended variable
* The module `udp_handler` is using the `Authentication` service but wasn't importing the module
> fix a few problems

- rosapi/scripts/rosapi_node
- rosapi/src/rosapi/proxy.py
Globs were passed as empty lists from rosapi node to proxy.py
Also fixes #349
> Fixes passing of globs to proxy

- rosbridge_server/scripts/rosbridge_tcp.py
- rosbridge_server/scripts/rosbridge_udp.py
- rosbridge_server/scripts/rosbridge_websocket.py
- rosbridge_server/src/rosbridge_server/tcp_handler.py
- rosbridge_server/src/rosbridge_server/udp_handler.py
- rosbridge_server/src/rosbridge_server/websocket_handler.py
> rosbridge_server: Publish number of connected clients on latched topic.

- rosbridge_library/package.xml
- rosbridge_library/src/rosbridge_library/capabilities/subscribe.py
- rosbridge_library/src/rosbridge_library/internal/cbor_conversion.py
- rosbridge_library/src/rosbridge_library/util/cbor.py
- rosbridge_library/test/internal/test_cbor_conversion.py
Prefer system version with C speedups, but include pure Python implementation.
Fixes #375
> Inline cbor library

- rosbridge_server/src/rosbridge_server/websocket_handler.py
* Decorate most handlers which were previously failing silently.
* Use a try block in the @coroutine, it refused double decoration.
* Always raise after logging, so Tornado sees the Exception too.
* Only warn when racing to write to a closed WebSocket.
> Log Tornado handler exceptions

- .travis.yml
refer to https://github.com/RobotWebTools/depthcloud_encoder/pull/15
> Update travis config to test melodic

- .travis.yml
- rosapi/src/rosapi/params.py
_It would be prudent to start running the tests in both 2 and 3._  https://github.com/RobotWebTools/rosbridge_suite/issues/401#issuecomment-512069249
> Travis CI: Look for Python syntax errors and undefined name

- rosbridge_library/package.xml
- rosbridge_server/package.xml
Precisely what the title says. It also removes an unused dependency.
> Update rosbridge_suite packages' dependencies.

- rosapi/src/rosapi/proxy.py
Updates import to match eloquent update
Update get_service_info to get_service_server_info
> Update rosapi/proxy.py to match eloquent API

- rosbridge_server/src/rosbridge_server/autobahn_websocket.py
- rosbridge_server/test/websocket/test_smoke.py
Fixes #448
@mikepurvis does this fix your problem?
> Fix Autobahn WebSocket vs. Python 3

- rosbridge_library/src/rosbridge_library/internal/publishers.py
- rosbridge_library/src/rosbridge_library/internal/ros_loader.py
- rosbridge_library/src/rosbridge_library/internal/subscription_modifiers.py
- rosbridge_server/src/rosbridge_server/autobahn_websocket.py
Fix some nitpicks with concurrency and un-silence some failures.
> Concurrency review

- rosbridge_server/launch/rosbridge_websocket.launch
- rosbridge_server/scripts/rosbridge_websocket.py
> Expose autobahn externalPort parameter

- ROSBRIDGE_PROTOCOL.md
I mistakenly wrote an old version of the service name here.
> Fix line in docs

- rosbridge_server/launch/rosbridge_websocket.launch
Hi all,
This pull-request add a new parameter to select the output on screen or log (like default).
> Output node parameter
