RobotWebTools/rosbridge_suite

rosapi/src/rosapi/proxy.py

Before, get_topics() only returned published topics and get_topic_type() only returned the topic type for published topics. Resolves #173.

Make get_topics() and get_topic_type() reference the full list of active topics

---

rosbridge_server/scripts/rosbridge_websocket.py

This enables tcp_nodelay for websockets fixing issue #171.

Enabled TCP nodelay in Websocket handler

---

rosbridge_library/package.xml

All msgs except `geometry_msgs` are only used in the tests. The `<test_depend>` tag will make sure the generated .debs will not depend on them.
`geometry_msgs` is used to generate a message for a test, and the following thread suggested to still use `<build_depend>` for that: http://answers.ros.org/question/115526/is-test_depend-actually-used-for-anything/

Use <test_depend> for test dependencies

---

rosbridge_server/scripts/rosbridge_websocket.py

This PR solves issue #181 for me.
The default ROS SIGINT handler is used and on shutdown the tornado server is stopped.

Stop IOLoop on shutdown.

---

rosbridge_server/scripts/rosbridge_tcp.py
rosbridge_server/scripts/rosbridge_websocket.py

This is an extension of #182 - ```rosbridge_tcp``` also didn't properly release its socket on node shutdown.
In addition, ```rosbridge_websocket``` now retries connecting, rather than breaking with an exception. This is useful in cases where we want to replace an old node, but the old node has not released its socket quickly enough for the new one to reopen it instantly.

improve shutdown handling

---

rosbridge_server/scripts/rosbridge_tcp.py
rosbridge_server/scripts/rosbridge_websocket.py
rosbridge_server/setup.py
rosbridge_server/src/rosbridge_server/__init__.py
rosbridge_server/src/rosbridge_server/tcp_handler.py
rosbridge_server/src/rosbridge_server/websocket_handler.py

These changes move `RosbridgeWebSocket` and `RosbridgeTcpServer` into their own exported modules.  This allows an implementer to include the ws handler in a Tornado Application or embed the tcp handler in another node.
I wanted to do two things with my ROS node:
* Run a static or dynamic web server hitting the same state/logic class as rospy pub/sub.
* Decentralize rosbridge and add it as a handler on that web server.
This simplifies the webapp, it no longer needs to make any assumptions or queries about where to find rosbridge.  In this case, rosbridge is treated as a node component as opposed to a service riding on the graph, with the caveat that topic pub/sub implementations may override settings from elsewhere in the same node.

Refactor ws and tcp handlers for external use

---

rosbridge_server/launch/rosbridge_websocket.launch

This allows downstream packages with roslaunch_add_file_check tests to pass.

Add default strings for certfile and keyfile

---

rosbridge_library/package.xml
rosbridge_library/src/rosbridge_library/internal/message_conversion.py
rosbridge_library/src/rosbridge_library/protocol.py
rosbridge_server/src/rosbridge_server/websocket_handler.py

Via #169 
Allows binary information to be transmitted as BSON objects when the binary_encoding flag is set to bson.

BSON Encoding for Binary Objects

---

rosbridge_server/scripts/rosbridge_tcp.py

After killing (Ctrl-C) a rosbridge_tcp server instance which has
connected clients, starting a new instance (on the same port) can
fail with the error: '[Errno 98] Address already in use'. Although the
node retries until the server starts, this can take up to a few minutes.
Instruct the ThreadingTCPServer to allow the reuse of the same address.

Allow TCP Server to reuse address after restart

---

rosbridge_library/src/rosbridge_library/protocol.py

This prevents performance problems when multiple clients are subscribing to high frequency topics.
Fixes #203

Address Protocol delay_between_messages performance bottleneck

---

rosbridge_server/launch/rosbridge_tcp.launch
rosbridge_server/launch/rosbridge_udp.launch
rosbridge_server/launch/rosbridge_websocket.launch
rosbridge_server/scripts/rosbridge_tcp.py
rosbridge_server/scripts/rosbridge_udp.py
rosbridge_server/scripts/rosbridge_websocket.py
rosbridge_server/src/rosbridge_server/tcp_handler.py
rosbridge_server/src/rosbridge_server/udp_handler.py
rosbridge_server/src/rosbridge_server/websocket_handler.py

This is a follow-up to #204 
* make parameters accessible via parameter server for all three versions
* remove old advertise_service parameters
* UDP and TCP can't do SSL
* TCP can't authenticate yet (because the RosbridgeTcpSocket class is instantiated for each request and hence does not hold state)
* UDP does not take a hostname or address, but rather an interface
**Note:** I haven't tested these changes yet! I'll be able to do so tomorrow, at least to see whether the launch files still work. I only have access to a system using ```rosbridge_websocket``` not the TCP or UDP version.

clean up parameters and handling

---

rosbridge_server/scripts/rosbridge_websocket.py

This allows the server to shut down via SIGINT or SIGTERM during its listen() retry loop.

Abort websocket server listen() retry on shutdown

---

.gitignore
rosbridge_server/scripts/rosbridge_udp.py

* Update `.gitignore`
* Isolate rosbridge_server libraries from unnecessary imports
* Stop UDP server on ROS shutdown

Fix UDP handler shutdown

---

rosbridge_library/src/rosbridge_library/internal/pngcompression.py

fromstring() method was completely removed since pillow 3.0.0 (https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst#300-2015-10-01) and now has a direct replacement.

Fixed deprecated code in pillow

---

rosbridge_library/src/rosbridge_library/internal/message_conversion.py

Correction issue #240, according to the [ROS message convention](http://wiki.ros.org/msg#line-47) for the int64 type.

Type conversion convention correction, correcting issue #240

---

rosapi/src/rosapi/objectutils.py

As mentioned by @T045T, this is a fix that should be its own commit and pull request, rather than a part of pull request #238.

Fixed time object field definitions to match documentation.

---

rosbridge_server/launch/rosbridge_websocket.launch

Without better doc, one does not understand why no topics are published. I thought, something is broken.
With this defaults, everything is working out of the box. And for a more secure setup, one can change it.

Fix: Set default to publish all topics

---

rosbridge_server/launch/rosbridge_tcp.launch
rosbridge_server/launch/rosbridge_udp.launch

Without these modifications, the rosapi node fails because some rosparams are not defined properly before:
```
Traceback (most recent call last):
File "/home/user/overlay_ws/src/rosapi/scripts/rosapi_node", line 211, in <module>
get_globs()
File "/home/user/overlay_ws/src/rosapi/scripts/rosapi_node", line 50, in get_globs
for element in rospy.get_param('~topics_glob', [])[1:-1].split(',')
AttributeError: 'list' object has no attribute 'split'
[rosapi-2] process has died ..........
```
Now the launchfiles comply to the websocket version.
P.s.
If somebody needs to avoid this crash urgently without patching the files: 
- Start a roscore
- Start the rosbridge_websocket.launch, which defines the necessary params and kill it after the initialization
- Start the tcp or udp launch file for …

Fixed the launch files for the tcp and udp service

---

rosbridge_library/src/rosbridge_library/internal/message_conversion.py
rosbridge_library/src/rosbridge_library/protocol.py
rosbridge_server/launch/rosbridge_tcp.launch
rosbridge_server/scripts/rosbridge_tcp.py
rosbridge_server/src/rosbridge_server/tcp_handler.py

Related to https://github.com/RobotWebTools/rosbridge_suite/issues/253
This commit allows users to switch to a full-duplex transmission of BSON messages and therefore eliminates the need for a base64 encoding of binary data when running in this mode. 
The new mode is **fully optional** and **is not activated by default**.
You can use the new mode by starting:
- roslaunch rosbridge_server rosbridge_tcp.launch bson_only_mode:=True
or
- rosbridge_tcp.py --bson_only_mode 
Your rosbridge_server will now only expect and transmit data in BSON.
This PR can also provide an improvement for problems like in https://github.com/RobotWebTools/roslibjs/issues/126, 
because the TCP handler can make some assumptions on the length of the message when using BSON. This is due to the length field that is …

Implemented a bson_only_mode flag for the TCP version of rosbridge

---

rosbridge_library/src/rosbridge_library/protocol.py

https://github.com/RobotWebTools/rosbridge_suite/issues/271
Quite likely want a cleaner solution that reconciles one place for a default of `False` to occur.  But a PR in the meantime to unblock current breakage of rosbridge_websocket

Prevent a KeyError when bson_only_mode is unset.

---

rosbridge_server/launch/rosbridge_websocket.launch
rosbridge_server/scripts/rosbridge_tcp.py
rosbridge_server/scripts/rosbridge_websocket.py
rosbridge_server/src/rosbridge_server/websocket_handler.py

This PR shall prevent bson_only_mode to be undefined at any time when using the websocket version of ROSBridge. This PR targets the problem described in https://github.com/RobotWebTools/rosbridge_suite/issues/271 .
When this change seems fine, i could also apply it on the udp version of ROSBridge.
Is there any UDP testclient?

Set default for bson_only_mode in websocket handler and launch file.

---

rosapi/README.md

There was a breaking change introduced by PR #238 
This change now requires all rosapi users to configure their globs to allow any topic/service/param information to be returned.
I've added a README which documents these new parameters along with two example launch configurations.
Please let me know if I've understood this feature correctly.
@MasterEric @T045T

Document glob

---

rosbridge_server/launch/rosbridge_websocket.launch

expose binary_encoder rosparam that was hidden in deep depth

---

rosapi/src/rosapi/params.py

To fix
```
[/rosapi ERROR 1498735222.314929]: Error processing request: has_param() takes exactly 2 arguments (1 given)
['Traceback (most recent call last):\n', '  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 625, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/home/jihoonl/work/ros/webtools/src/rosbridge_suite/rosapi/scripts/rosapi_node", line 190, in delete_param\n    rosapi.params.delete_param(request.name, params_glob)\n', '  File "/home/jihoonl/work/ros/webtools/src/rosbridge_suite/rosapi/src/rosapi/params.py", line 97, in delete_param\n    if has_param(name):\n', 'TypeError: has_param() takes exactly 2 arguments (1 given)\n']
[/rosbridge_websocket ERROR …
```

fix delete_param in rosapi

---

rosbridge_library/src/rosbridge_library/capabilities/advertise.py
rosbridge_library/src/rosbridge_library/capabilities/advertise_service.py
rosbridge_library/src/rosbridge_library/capabilities/call_service.py
rosbridge_library/src/rosbridge_library/capabilities/publish.py
rosbridge_library/src/rosbridge_library/capabilities/subscribe.py
rosbridge_library/src/rosbridge_library/capabilities/unadvertise_service.py

added topic and service names to warnings in order to improve immediate debugability; minor linting

added topic and service names to warnings

---

rosbridge_library/CMakeLists.txt
rosbridge_library/test/capabilities/test_call_service.py
rosbridge_library/test/capabilities/test_subscribe.py

* add timeout and a proper service callback wait-logic instead of sleep.
* add queue_size in rospy publisher

Fixing errors in test.

---

ROSBRIDGE_PROTOCOL.md

Fix #280 by modifying the document to match code. Subscriber's default queue_length is 0.

Fix subscrider's default queue_length in documentation to match code

---

rosapi/src/rosapi/proxy.py

The service `/rosapi/action_servers` uses a filter function on topic names to detect action servers.
This function worked only with topics of type `/namespace/goal`, with only one namespace.
It is now capable of detecting for example `/ns1/ns2/server/goal` (when all goal, success, cancel, feedback and status topics are alive, of course).
The service returns an array of the full namespaces, `/ns1/ns2/server` being one of them here for example

Fixed action_servers filter to allow more than one namespace

---

.travis.yml
rosbridge_library/test/capabilities/test_call_service.py
rosbridge_library/test/internal/test_services.py

Our Travis config had ```dist: xenial```, which is not currently supported (see https://github.com/travis-ci/travis-ci/issues/7260).
With that fixed, some tests were still failing, to I fixed those as well (they tried to access ```/rosout/set_logger_level```, which ```rostest``` hides for some reason).
The Travis build passed for my fork after those changes :)

Fix Travis config

---

rosbridge_library/src/rosbridge_library/capabilities/advertise_service.py
rosbridge_library/src/rosbridge_library/capabilities/service_response.py
rosbridge_library/src/rosbridge_library/capabilities/unadvertise_service.py
rosbridge_library/test/capabilities/test_capabilities.test
rosbridge_library/test/capabilities/test_service_capabilities.py

Primarily, this should fix #265 (but only if a service is actually unadvertised. If it just loses connection and does not answer, the client will still busy-wait).
I added new rostests to confirm the fix works, and discovered a few minor bugs in the process. Since these changes are only related via the rostest, I'd prefer not to squash-merge this PR.

Service fixes

---

rosbridge_library/src/rosbridge_library/capabilities/advertise.py
rosbridge_library/src/rosbridge_library/capabilities/publish.py
rosbridge_library/src/rosbridge_library/internal/publishers.py
rosbridge_library/test/capabilities/test_advertise.py
rosbridge_library/test/internal/publishers/test_publisher_manager.py
rosbridge_server/launch/rosbridge_tcp.launch
rosbridge_server/launch/rosbridge_udp.launch
rosbridge_server/launch/rosbridge_websocket.launch
rosbridge_server/scripts/rosbridge_tcp.py
rosbridge_server/scripts/rosbridge_udp.py
rosbridge_server/scripts/rosbridge_websocket.py
rosbridge_server/src/rosbridge_server/tcp_handler.py
rosbridge_server/src/rosbridge_server/udp_handler.py
rosbridge_server/src/rosbridge_server/websocket_handler.py

Pull request #247 introduces a 10 second delay to mitigate issue #138.
This change makes this delay configurable by passing an argument either
on the command line or when including a launch file.
Usage example:
```xml
<launch>
<include file="$(find rosbridge_server)/launch/rosbridge_websocket.launch">
<arg name="unregister_timeout" value="5.0"/>
</include>
</launch>
```
Closes #320

Make unregister_timeout configurable

---

rosbridge_library/src/rosbridge_library/protocol.py

The problem for me was that after subscribing, rosbridge didn't send messages back to client with no errors.
Code failed silently, because has_binary was called out in try catch block.

Fix typo in function call

---

rosbridge_library/src/rosbridge_library/capabilities/advertise.py
rosbridge_library/src/rosbridge_library/capabilities/publish.py
rosbridge_library/src/rosbridge_library/protocol.py

Pretty straight forward, remove has_key method for dict since it is removed in python 3. Changes are still backwards compatible with python 2.x.

removing has_key for python3, keeping backwards compatibility

---

rosbridge_server/launch/rosbridge_websocket.launch
rosbridge_server/scripts/rosbridge_websocket.py
rosbridge_server/src/rosbridge_server/websocket_handler.py

Tornado has its own per-message deflate compression option, which
compresses each WebSocket message.  The compression level should be
roughly equivalent to PNG compression, depending on whether the message is
JSON or binary (CBOR).  The encoding/decoding time will be much faster
than protocol PNG compression.
This param should be enabled when wire size is important, e.g. not
connecting to localhost.

Add param to enable ws per-message deflate

---

rosapi/scripts/rosapi_node
rosapi/src/rosapi/proxy.py

Hello,
When using `rosapi` in the development of web applications for the PR2 robot, I was facing the problem that the call for the `/rosapi/topics` service was extremely slow (operating with over 1200 topics).
Looking into the problem, it seems that getting the types was taking a lot of time:
```python
In [3]: time topics = get_topics(['*'])
CPU times: user 152 ms, sys: 0 ns, total: 152 ms
Wall time: 183 ms
In [4]: time types = get_topics_types(topics, ['*'])
CPU times: user 1min 18s, sys: 428 ms, total: 1min 18s
Wall time: 2min 6s
```
By using the `Master.getTopicTypes()` we can get equivalent results (the order changes) with better performance:
```python
In [5]: time new_topics, new_types = get_topics_and_types(['*'])
CPU times: user 244 ms, sys: 0 ns, total: 244 ms
Wall time: 297 ms …
```

Use getTopicTypes() in /rosapi/get_topics for increased performance

---

rosbridge_server/src/rosbridge_server/websocket_handler.py

Handle BadYieldError in Tornado <4.5.0

---

rosbridge_msgs/CMakeLists.txt
rosbridge_msgs/msg/ConnectedClient.msg
rosbridge_msgs/msg/ConnectedClients.msg
rosbridge_msgs/package.xml
rosbridge_server/package.xml
rosbridge_server/scripts/rosbridge_websocket.py
rosbridge_server/src/rosbridge_server/__init__.py
rosbridge_server/src/rosbridge_server/client_mananger.py
rosbridge_server/src/rosbridge_server/websocket_handler.py

Latches a list of all connected clients, where each client is described by
- the client's IP address
- the time the client connected
This only works for the websocket server for now. Let me know if this is something useful. If so, then I will look into adding this functionality also to the other backends.

Additional client information websocket

---

rosbridge_library/src/rosbridge_library/internal/publishers.py

in my use case logging warning was causing the publish manager to fail. fixed it.

fixed logwarn msg formatting in publishers

---

rosbridge_server/scripts/rosbridge_websocket.py
rosbridge_server/src/rosbridge_server/websocket_handler.py

I've noticed that if the connection between websocket client and server is closed unexpectedly, a client can be marked as connected forever on the server. With only one client I managed to make the `client_count` topic grow higher than 3 by disabling wifi while rosbridge was connected.
Tornado has parameters to enable the keep-alive ping which is integrated into [websocket protocol](https://tools.ietf.org/html/rfc6455#section-5.5.2). I exposed `websocket_ping_interval` and `websocket_ping_timeout` as ROS and CLI parameters. [Tornado documentation of those parameters](https://www.tornadoweb.org/en/stable/web.html#tornado.web.Application.settings).
I've set `websocket_ping_interval` to 0, to let this feature disabled by default. Because if someone use rosbridge with a buggy websocket …

Add settings for websocket timeout

---

rosapi/msg/TypeDef.msg
rosapi/scripts/rosapi_node
rosapi/src/rosapi/objectutils.py

There is currently no access to the constants of messages/services via rosbridge.
These new lines added to the current project permit us to get an access to these values and use them if needed. `constnames` and `constvalues` variables are added to TypeDef.msg.

Access to constants of messages/services via rosbridge 

---

rosbridge_server/src/rosbridge_server/websocket_handler.py

Fixes #403 v2 : yield infinite lock

---

rosapi/package.xml
rosapi/scripts/rosapi_node
rosapi/src/rosapi/glob_helper.py
rosapi/src/rosapi/objectutils.py
rosapi/src/rosapi/params.py
rosapi/src/rosapi/proxy.py
rosapi/srv/DeleteParam.srv
rosapi/srv/GetParam.srv
rosapi/srv/GetParamNames.srv
rosapi/srv/HasParam.srv
rosapi/srv/SetParam.srv
rosbridge_library/src/rosbridge_library/internal/ros_loader.py

This PR focuses on porting `rosapi` package to ROS2.
See https://github.com/ros2/rosbridge_suite/issues/2 for the current overall progress.

Porting rosapi package.

---

rosbridge_server/src/rosbridge_server/websocket_handler.py

#413 added a check for the result of tornados WebSocketHandler.write_message and is throwing WebSocketClosedError if its None.
WebSocketHandler.write_message does return a Future since version 4.3.0. ([tornado write_message doc](https://www.tornadoweb.org/en/stable/websocket.html#tornado.websocket.WebSocketHandler.write_message))
I added a check to only raisie the Error when version is >4.3.0, to prevent anyone using a tornado version <4.3.0 to have a WebSockedClosedError for every message (see #418).

Fixes #418: WebSocketClosedError Spam

---

rosapi/scripts/rosapi_node
rosapi/src/rosapi/glob_helper.py
rosapi/src/rosapi/params.py
rosapi/srv/DeleteParam.srv
rosapi/srv/GetParam.srv
rosapi/srv/GetParamNames.srv
rosapi/srv/HasParam.srv
rosapi/srv/SetParam.srv
rosbridge_library/src/rosbridge_library/capabilities/advertise.py
rosbridge_library/src/rosbridge_library/capabilities/advertise_service.py
rosbridge_library/src/rosbridge_library/capabilities/call_service.py
rosbridge_library/src/rosbridge_library/capabilities/publish.py
rosbridge_library/src/rosbridge_library/capabilities/subscribe.py
rosbridge_library/src/rosbridge_library/internal/message_conversion.py
rosbridge_library/src/rosbridge_library/internal/publishers.py
rosbridge_library/src/rosbridge_library/internal/ros_loader.py
rosbridge_library/src/rosbridge_library/internal/services.py
rosbridge_library/src/rosbridge_library/internal/subscribers.py
rosbridge_library/src/rosbridge_library/protocol.py
rosbridge_library/src/rosbridge_library/rosbridge_protocol.py
rosbridge_msgs/CMakeLists.txt
rosbridge_msgs/msg/ConnectedClient.msg
rosbridge_msgs/package.xml
rosbridge_server/scripts/rosbridge_websocket.py
rosbridge_server/src/rosbridge_server/__init__.py
rosbridge_server/src/rosbridge_server/client_mananger.py
rosbridge_server/src/rosbridge_server/websocket_handler.py

See https://github.com/ros2/rosbridge_suite/issues/3.
With this patch, all the code from the entrypoint (`Websocket server`) up to the internal libraries should be ROS2-compatible, and no references to `rclpy` or ROS1 code should remain.
<details><summary>Details</summary>
- All the ROS1 code that involves publishers, subscribers and services now need a `rclpy.node.Node` handle to work.
- `RosbridgeWebsocketNode` in `rosbridge_websocket` module was converted to a ROS2 node because it's near the entry point of the application. A reference to it shall be used to generate publishers, subscribers and service clients where necessary.
- Besides routing the node handle to all the points of the program where it was required (the deepest point from the entrypoint is the `internal` package), there …

Porting rosbridge library (capabilities and internal) to ROS2.

---

rosbridge_msgs/package.xml

[ROS 2] rosbridge_msgs: add missing build type

---

rosbridge_server/src/rosbridge_server/autobahn_websocket.py

Fixes a crash when sending data from rosbridge_server to client when running server with bson_only_mode=True 
autobahn.websocket.WebSocketServerProtocol.sendMessage asserts whether message is of type bytes, which fails for message of type bson.BSON. Hence a conversion is required.

autobahn_websocket.py: Convert BSON to bytes before call to sendMessage

---

rosbridge_library/src/rosbridge_library/internal/subscribers.py

Under Python 3, values() returns a `dict_values` iterator, and because that object is used outside the mutex, we were getting `RuntimeError: dictionary changed size during iteration` under some circumstances. This creates a copy of the values, restoring the Python 2 behaviour and fixing the problem.

Python 3 fix for dict::values

---

rosbridge_server/CMakeLists.txt

This is friendlier to using alternative pythons, and the recommended approach:
http://docs.ros.org/melodic/api/catkin/html/howto/format2/installing_python.html#scripts

Install scripts with catkin_install_python.

---

ROSBRIDGE_PROTOCOL.md
rosapi/CMakeLists.txt
rosapi/scripts/rosapi_node
rosapi/src/rosapi/objectutils.py
rosapi/srv/TopicsAndRawTypes.srv
rosbridge_library/src/rosbridge_library/capabilities/subscribe.py
rosbridge_library/src/rosbridge_library/internal/subscribers.py
rosbridge_server/CMakeLists.txt
rosbridge_server/test/websocket/test_cbor_raw.py
rosbridge_server/test/websocket/test_cbor_raw.test

The CBOR compression is already a huge win over JSON or PNG encoding, but it’s still suboptimal in some situations. This PR adds support for getting messages in their raw binary (ROS-serialized) format. This has benefits in the following cases:
- Your application already knows how to parse messages in bag files (e.g. using [rosbag.js](https://github.com/cruise-automation/rosbag.js)), which means that now you can use consistent code paths for both bags and live messages.
- You want to parse messages as late as possible, or in parallel, e.g. only in the thread or WebWorker that cares about the message. Delaying the parsing of the message means that moving or copying the message to the thread is cheaper when its in binary form, since no serialization between threads is necessary.
- You only …

Add cbor-raw compression

---

rosbridge_library/src/rosbridge_library/internal/message_conversion.py

When publishing a message to ROS (i.e. incoming from rosbridge_server's perspective), timestamps in the Header attributes all point to the same Time object iff the message contains multiple Header attributes (typically the case if a ROS message contains other ROS messages, e.g. ...Array-types) and rosparam use_sim_time is true. 
This commit fixes the issue.

Fixing wrong header/stamp in published ROS-messsages

---

rosbridge_server/CMakeLists.txt
rosbridge_server/test/websocket/test_cbor_raw.test
rosbridge_server/test/websocket/test_smoke.py
rosbridge_server/test/websocket/test_smoke.test

Intermittent test failures on kinetic are blocking PR merges.  I found that changing the client, not the server, affected the smoke tests more.  This change reduces the load.

Fix intermittent test smoke

---

rosbridge_server/launch/rosbridge_websocket.launch
rosbridge_server/scripts/rosbridge_websocket.py

For Kinetic 0.10.3 version don't add the allowNullOrigin option.
For everything else add it and default to True because that is
consistent with the original behaviour of this package.

Default to supporting local files as we had before Autobahn.

---

rosbridge_server/launch/rosbridge_websocket.launch

default websocket_external_port to port to mimic behavior in node

---

rosbridge_library/src/rosbridge_library/internal/subscription_modifiers.py
rosbridge_library/test/internal/subscribers/test_subscription_modifiers.py

`QueueMessageHandler.run` was holding onto its lock while writing out to the server.  Since the websocket server can block outgoing messages now, this was causing cross-client blocking by jamming up the rospy Subscriber thread.
By releasing the lock before writing, we let this handler work the way it was always intended.
The handler's internal queue was switched to a `deque` for simplicity.

Fix queue blocking

---

rosbridge_library/src/rosbridge_library/internal/subscribers.py

Protect critical sections in SubscriberManager which were previously unprotected from race conditions between clients.
Raise Exception when unsubscribe input is invalid instead of passing this condition silently.

Subscriber concurrency review

---

Dockerfile
README.md
rosbridge_library/test/internal/subscribers/test_subscription_modifiers.py
rosbridge_library/test/internal/test_internal.test
run_docker.sh

This script spins up a docker container with all rosbridge packages in a catkin workspace with sources mounted read-only and host networking.  Have been using something like it for a while, and thought the community might find it useful for quickly testing and iterating rosbridge.

Add script for dockerized development shell

---

rosbridge_library/src/rosbridge_library/capabilities/subscribe.py
rosbridge_library/src/rosbridge_library/internal/subscription_modifiers.py
rosbridge_server/src/rosbridge_server/autobahn_websocket.py

Fix backpressure deadlock

---

rosbridge_server/src/rosbridge_server/autobahn_websocket.py

Prevents errors during protocol shutdown from breaking other states.

Finish protocol in IncomingQueue thread
